FROM ruby:2.6.1-slim-stretch

RUN apt-get update && apt-get -y install \
  gcc \
  liblzma-dev \
  libsqlite3-dev \
  make \
  patch \
  zlib1g-dev \
  && apt-get clean && \
  rm -r /var/lib/apt/lists/*


COPY Gemfile Gemfile.lock /
RUN bundle install

WORKDIR /rails
COPY . /rails