_equator_dataplatform_default: &equator_dataplatform_default
  namespacePrefix: equator-dataplatform
  image: us.gcr.io/tmn-th-equator-ci/acm-dp--ocp--rails-demo--dev
  rails_host: rails--equator-dataplatform-<%- envTier %>.cicd.ascendmoney-dev.internal

equator_dataplatform:
  dev:
    <<: *equator_dataplatform_default
  
  staging: 
    <<: *equator_dataplatform_default
    
  qa:
    <<: *equator_dataplatform_default
  