_equator_dataplatform_default: &equator_dataplatform_default
  namespacePrefix: equator-dataplatform
  image: us.gcr.io/tmn-th-equator-ci/acm-dp--ocp--rails-demo--dev

equator_dataplatform:
  staging: 
    <<: *equator_dataplatform_default
    rails_host: rails--equator-dataplatform-staging.cicd.ascendmoney-dev.internal
    
  qa:
    <<: *equator_dataplatform_default
    rails_host: rails--equator-dataplatform-qa.cicd.ascendmoney-dev.internal
