version: "2.1"
services:
  rails:
    image: us.gcr.io/dataplatform-1363/acm-dp--ocp--rails-demo--dev
    build: 
      context: ../rails
      dockerfile: ../Dockerfile-rails
    network_mode: bridge
    tmpfs:
      - /rails/tmp/pids
    volumes:
      - rails_data:/data
      - rails_log:/rails/log
      - rails_tmp:/rails/tmp

volumes:
  rails_data: {}
  rails_log: {}
  rails_tmp: {}
