apiVersion: v1
kind: Service          
metadata:
  name: rails-http
  namespace: <%- namespacePrefix %>-<%- envTier %>
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    name: rails
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}